version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    target-branch: "main"
    reviewers:
      - "raffreitas"
    assignees:
      - "raffreitas"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
        update-types:
          - "minor"
          - "patch"
      microsoft-testing:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "coverlet*"
        update-types:
          - "minor"
          - "patch"
      github-actions:
        patterns:
          - "Microsoft.SourceLink.GitHub"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.NET.Test.Sdk"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    target-branch: "main"
    reviewers:
      - "raffreitas"
    assignees:
      - "raffreitas"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
